categories:
  - name: "🎯 General"
    description: "General discussions about Dungeon Game"
    emoji: "🎯"
    
  - name: "🤖 AI & Strategy" 
    description: "Discuss Q-Learning algorithms, strategies, and AI behavior"
    emoji: "🤖"
    
  - name: "💡 Ideas"
    description: "Feature requests, suggestions, and improvements"
    emoji: "💡"
    
  - name: "🆘 Help"
    description: "Get support, troubleshooting, and technical assistance"
    emoji: "🆘"
    
  - name: "🎉 Show & Tell"
    description: "Share your achievements, screenshots, and experiences"
    emoji: "🎉"
    
  - name: "🐛 Bug Reports"
    description: "Report issues and bugs you've encountered"
    emoji: "🐛"
